//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_DelegacionMunicipal.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imagenes()
        {
            this.Reporte = new HashSet<Reporte>();
        }
    
        public int idImagenes { get; set; }
        public byte[] imagen1 { get; set; }
        public byte[] imagen2 { get; set; }
        public byte[] imagen3 { get; set; }
        public byte[] imagen4 { get; set; }
        public byte[] imagen5 { get; set; }
        public byte[] imagen6 { get; set; }
        public byte[] imagen7 { get; set; }
        public byte[] imagen8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte> Reporte { get; set; }
    }
}
